import type { Metadata } from "next";
import { Cinzel, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ViewTransitions } from "next-view-transitions";

const cinzel = Cinzel({
	variable: "--font-cinzel",
	subsets: ["latin"],
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${cinzel.variable} ${geistSans.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col bg-background text-foreground">
                <Navbar />
                <main className="flex-1">
                    <div className="mx-auto max-w-6xl">
                        <ViewTransitions>
                            {children}
                        </ViewTransitions>
                    </div>
                </main>
                <Footer />
            </body>
        </html>
    );
}
